title : mp-strumenti.it
baseurl: "http://mp-strumenti.it"
description: "Handmade guitars and basses for passion and hobby. Based in Rome, Italy."
feed-description: "RSS Feeds for the website"
copyright: "2020"
markdown: kramdown

greeting: "Welcome"
headline: "Handmade guitars and basses for passion and hobby. Based in Rome, Italy."
logo: assets/images/logo.svg

image: /assets/img/og-image.png

author :
  name : MP Strumenti
  headline: "Handmade guitars and basses for passion and hobby. Based in Rome, Italy."
  image: assets/img/pic-72.jpg
  avatar: 
    src : assets/img/avatar.jpg
    srcset : 
      - assets/img/avatar-1x.jpg
      - assets/img/avatar-2x.jpg
      - assets/img/avatar-3x.jpg
      - assets/img/avatar-4x.jpg


# Sass settings
sass:
  sass_dir: assets/css
  style: compressed

# Set collections
collections:
  instruments:
    output: true
    models:
      output: true
    series:
      output: true
      pragma:
        output: true
        title: Serie Pragma
plugins:
  - jekyll-sitemap

lang: it


# Manifest settings (Used to make manifest.json)
# Edit manifest.json directly with icon information
manifest_name: mp-strumenti.it
manifest_short_name: "mp-strumenti.it" # Appears in "Add to home screen" dialogues
manifest_lang: it
manifest_background_color: white
manifest_display: standalone